### ISSUE TITLE
Drawing methods do not take screen rotation into account

### ISSUE THREAD

**Issue by djairjr** [adafruit/Adafruit_CircuitPython_Pixel_Framebuf#10]
From what I can understand, the drawing methods derive from the adafruit_framebuf library and do not take screen rotation into account.

I wrote a function for my games' menu system that I believe could be a way forward.

From what I can understand, the drawing methods derive from the adafruit_framebuf library and do not take screen rotation into account.

I wrote a function for my games' menu system that I believe could be a way forward. My screen is rotated 270 degrees, with this setup.

```
spi = board.SPI()
pixel_pin = board.D10 #board.MOSI

# Setting up the Neopixel Pannel - 16 x 16 Version
how_many = 2
panel_width = 16 # Two Pannels Wide.
panel_height = 16
num_pixels = how_many * panel_width * panel_height

pixels = neopixel.NeoPixel_SPI(
    spi,
    num_pixels, 
    brightness=0.2,
    auto_write=False,
)

# When 16x16 Using original Adafruit_Pixel_Framebuf Library
screen = PixelFramebuffer(
    pixels,
    panel_width , 
    panel_height * how_many, # What?
    rotation = 1, # Simple change rotation...
)

def display_bitmap(self,screen, tile_width, tile_height, bitmap, frame_index=0):
    '''
    Draw a bitmap or sprite_sheet taking in account the screen rotation
    '''
    self.screen = screen
    bitmap_width = bitmap.width
    bitmap_height = bitmap.height
    tiles_per_row = bitmap_width // tile_width
    tiles_per_column = bitmap_height // tile_height
    
    if tiles_per_row * tiles_per_column > 1:
        total_tiles = tiles_per_row * tiles_per_column
        if frame_index >= total_tiles:
            raise ValueError("Tile index out of range")
        tile_x = (frame_index % tiles_per_row) * tile_width
        tile_y = (frame_index // tiles_per_row) * tile_height
    else:
        tile_x = 0
        tile_y = 0
    
    for x in range(tile_width):
        for y in range(tile_height):
            pixel_color = bitmap[tile_x + x, tile_y + y]
            # Extract 16 bits RGB Components
            r = (pixel_color >> 11) & 0x1F  # RED
            g = (pixel_color >> 5) & 0x3F   # GREEN
            b = pixel_color & 0x1F          # BLUE
            # Convert  components from 16 bits to 8 bits (0-255)
            r = (r * 255) // 31
            g = (g * 255) // 63
            b = (b * 255) // 31

            # The entire magic happens here.
            # This setup will draw a pixel, with rotation corrected
            if self.screen.rotation == 0:
                self.screen.pixel(x, 31 - y, (r, g, b))
            elif self.screen.rotation == 1:
                self.screen.pixel(31 - y, 15 - x, (r, g, b))
            elif self.screen.rotation == 2:
                self.screen.pixel(15 - x, y, (r, g, b))
            elif self.screen.rotation == 3:
                self.screen.pixel(y, x, (r, g, b)) 
```

**Comment by djairjr** [comment]
Sorry I couldn't help more. If I had a little more knowledge, I would have already changed the library to include this solution. Still, I'll try to work on a fork of it and see what I can do.

**Comment by FoamyGuy** [comment]
@djairjr If you use only the basic drawing functions like `pixel()` and `line()` is it working for you, or if you try it on a single panel instead of 2? If you're still having trouble with this can you also share photos and / or a wiring diagram that shows how your panels are wired to the microcontroller? I suspect the order of the pixels within the panels and how they are wired together and then into the microcontroller could factor in to getting the size and rotation working properly, though I don't have an easy way to test multiple panels. 

As far as I can tell the existing rotation parameter seems to behave as expected.  I tested on a neopixel featherwing with this code:

```
pixel_framebuf = PixelFramebuffer(
    pixels,
    pixel_width,
    pixel_height,
    alternating=False,
    rotation=0,
)
pixel_framebuf.pixel(0, 0, 0xFFFF00)
pixel_framebuf.display()
```
And I substituted the other valid rotations `1`, `2`, and `3` in for the value of the `rotation` argument. In each case it is drawing the single pixel where it is expected: rotation 0 = top left, rotation 1 = top right, rotation 2 = bottom right, rotation 3 = bottom left. 

I tested briefly with pixel_framebuf.line() as well and it seems to behave as expected too.

**Comment by FoamyGuy** [comment]
Closing this for now as I believe the library is behaving as expected. If you return to this and are still having trouble feel free to re-open this or create a new issue. Please include photos of the wiring if so.
